name: Paperstack Core

on:
  workflow_call:
    inputs:
      search-arxiv:
        description: 'Search Arxiv?'
        required: true
        type: 'boolean'
      search-scholar:
        description: 'Search Semantic Scholar?'
        required: true
        type: 'boolean'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: |
        python paperstack.py ${{ inputs.search-arxiv && '--search-arxiv' || '' }} ${{ inputs.search-scholar && '--search-semantic-scholar' || '' }}
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        OPENAI_API_TOKEN: ${{ secrets.OPENAI_API_TOKEN }}