name: Paperstack (Long)

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  call-core:
    uses: ./.github/workflows/core.yml
    secrets: inherit
    with:
      search-arxiv: true
      search-scholar: true