name: Paperstack

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      search-arxiv:
        description: 'Search Arxiv?'
        required: false
        default: 'false'
      search-scholar:
        description: 'Search Semantic Scholar?'
        required: false
        default: 'false'
            
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: |
        python paperstack.py \
          ${{ github.event.inputs.search-arxiv == 'true' && '--search-arxiv' || '' }} \
          ${{ github.event.inputs.search-scholar == 'true' && '--search-semantic-scholar' || '' }}
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        OPENAI_API_TOKEN: ${{ secrets.OPENAI_API_TOKEN }}